# Generated by Django 4.2.2 on 2023-07-11 04:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tarih',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
