# Generated by Django 4.2.2 on 2023-07-12 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image_app', '0003_alter_image_tarih'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='nickname',
        ),
        migrations.AddField(
            model_name='image',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
